version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 50
  ignore:
  - dependency-name: commander
    versions:
    - "> 4.1.1"
  - dependency-name: eslint
    versions:
    - "> 6.8.0"
  - dependency-name: "@koa/router"
    versions:
    - "> 8.0.8"
  - dependency-name: "@koa/router"
    versions:
    - "> 9.0.1"
  - dependency-name: sharp
    versions:
    - "> 0.25.4"
  - dependency-name: terser-webpack-plugin
    versions:
    - "> 4.2.3"
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - "> 2.34.0"
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: aws-sdk
    versions:
    - 2.833.0
    - 2.834.0
    - 2.835.0
    - 2.836.0
    - 2.838.0
    - 2.840.0
    - 2.841.0
    - 2.843.0
    - 2.844.0
    - 2.845.0
    - 2.846.0
    - 2.847.0
    - 2.848.0
    - 2.849.0
    - 2.850.0
    - 2.851.0
    - 2.852.0
    - 2.853.0
    - 2.854.0
    - 2.855.0
    - 2.856.0
    - 2.858.0
    - 2.859.0
    - 2.860.0
    - 2.861.0
    - 2.862.0
    - 2.863.0
    - 2.864.0
    - 2.865.0
    - 2.866.0
    - 2.867.0
    - 2.868.0
    - 2.869.0
    - 2.870.0
    - 2.871.0
    - 2.874.0
    - 2.875.0
    - 2.876.0
    - 2.878.0
    - 2.879.0
    - 2.880.0
    - 2.881.0
    - 2.882.0
    - 2.883.0
    - 2.884.0
    - 2.885.0
    - 2.886.0
    - 2.889.0
    - 2.890.0
    - 2.892.0
    - 2.893.0
    - 2.894.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.37
    - 14.14.39
    - 15.0.0
  - dependency-name: chart.js
    versions:
    - 3.0.2
    - 3.1.0
    - 3.1.1
  - dependency-name: ts-loader
    versions:
    - 8.0.14
    - 8.0.16
    - 9.0.0
    - 9.1.0
  - dependency-name: is-root
    versions:
    - 3.0.0
  - dependency-name: js-yaml
    versions:
    - 4.0.0
    - 4.1.0
  - dependency-name: css-loader
    versions:
    - 5.0.2
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.1
  - dependency-name: cssnano
    versions:
    - 4.1.11
  - dependency-name: "@types/sharp"
    versions:
    - 0.27.3
    - 0.28.0
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.9
  - dependency-name: redis
    versions:
    - 3.1.0
  - dependency-name: systeminformation
    versions:
    - 5.0.11
    - 5.0.6
    - 5.0.8
    - 5.0.9
    - 5.1.1
    - 5.1.2
    - 5.2.1
    - 5.2.5
    - 5.3.0
    - 5.3.1
    - 5.6.1
    - 5.6.10
    - 5.6.2
    - 5.6.3
    - 5.6.5
    - 5.6.7
    - 5.6.9
  - dependency-name: jsdom
    versions:
    - 16.5.0
    - 16.5.2
  - dependency-name: "@types/jsdom"
    versions:
    - 16.2.9
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: jsonld
    versions:
    - 3.3.0
    - 3.3.2
    - 5.0.0
  - dependency-name: "@types/js-yaml"
    versions:
    - 4.0.0
  - dependency-name: probe-image-size
    versions:
    - 7.0.0
  - dependency-name: is-svg
    versions:
    - 4.2.2
  - dependency-name: vue-i18n
    versions:
    - 8.23.0
    - 8.24.0
    - 8.24.1
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: pureimage
    versions:
    - 0.2.6
    - 0.2.7
  - dependency-name: koa-views
    versions:
    - 7.0.0
  - dependency-name: "@types/jsonld"
    versions:
    - 1.5.3
    - 1.5.4
  - dependency-name: pug
    versions:
    - 3.0.2
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.2.2
  - dependency-name: "@types/koa"
    versions:
    - 2.11.7
    - 2.11.8
    - 2.13.0
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.0
  - dependency-name: dateformat
    versions:
    - 4.5.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
  - dependency-name: bull
    versions:
    - 3.21.0
    - 3.21.1
